# JoinOur
messages:
  general:
    no_permission: "&cYou do not have permission to use this command."
    not_player: "&cYou must be a player to use this command."
    command_disabled: "&cThat command has been disabled by the server owner"
  website:
    link: "https://example.com"
    hover_text: "&bVisit our website!"
  apply:
    link: "https://example.com/apply"
    hover_text: "&bApply for Staff!"
  discord:
    link: "https://example.com"
    hover_text: "&bChat on our Discord"
  forums:
    link: "https://example.com"
    hover_text: "&bChat on our forums!"
  twitter:
    link: "https://example.com"
    hover_text: "&bFollow us, but please not in real life."
enabled_commands:
  website: true
  apply: true # apply for staff
  discord: true
  forums: true
  twitter: true

other:
  disable_command_send_no_permission: false # If a command is disabled would you want to send the command disabled message or that the player doesn't have permission.